### ISSUE TITLE
Permissions set by storage api

### ISSUE THREAD

**Issue by ymatsush** [IBM/datapower-operator-chart#21]
Can I change the permissions on the paths set for storage api?
After implementing the following settings, the file could not be written because the permissions were as follows

- yaml
```
apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
spec:
  storage:
  - type: persistent
    path: /opt/ibm/datapower/drouter/config/GAPI
    size: 10Gi
    class: ibmc-file-silver
```

- permission
```
drouter@idg-test-0 config]$ ls -ld GAPI
drwxr-xr-x 2 65534 4294967294 4096 Dec 14 01:36 GAPI
```
